### ISSUE TITLE
[BUG] Package.json needed for install.

### ISSUE THREAD

**Issue by SkyWolf369** [nhcarrigan/TSProGen#11]
# Bug Report

## Describe the bug

Package can not be installed without an already existing package.json in the folder in which the user is attempting to install it. This hinders the effects of the package due to the fact that the package is meant to gen the json when ran. Therefore this bug blocks further development please fix when is convenient for you.
## Expected behavior

Allowed access to install the package before having a package.json in the users project directory

## Screenshots
None

## Additional information
None

**Comment by nhcarrigan** [comment]
I believe once this is actually published it can be installed globally, which will allow a direct `ts-pro-gen` CLI call in any directory.

**Comment by SkyWolf369** [comment]
All right
