### ISSUE TITLE
[FEAT] Install Node Modules (Multiple Package Manager Support)

### ISSUE THREAD

**Issue by creepinson** [nhcarrigan/TSProGen#22]
# Feature Request

## Is your feature request related to a problem? Please describe:

Every other ts project generator uses npm install, which would be a very nice addition to add to this package. However, the one thing I hate about these other ones is that they don't let you use package managers like yarn or pnpm.

## Describe the solution you'd like

You could use something like [Enquirer](https://www.npmjs.com/package/enquirer) to select a package manager, and then if you want you could write it to a config file in the user's home directory for future use. 

I'm going to make an example of what this might look like.

**Comment by nhcarrigan** [comment]
Not a bad idea! I'll open this up for contributions. 🙂

**Comment by creepinson** [comment]
![image](https://user-images.githubusercontent.com/11761863/97816025-22fa0b00-1c47-11eb-839e-453beeac1a1c.png)
![image](https://user-images.githubusercontent.com/11761863/97816036-32795400-1c47-11eb-9dce-de99f0f78b05.png)
Here is an example of enquirer.

**Comment by creepinson** [comment]
Alright so I've basically rewritten the code - I hope this won't be a problem. Below is a list of changes I'm going to add to a pr:

- Use template folder instead of copying from the root
- Use fs-extra package for copying the files from the template folder
- Use listr2 package to create a task list for installing the dependencies and creating the project.
  - Listr also adds a prompt function so I used it to prompt for the package manager

![unknown2](https://user-images.githubusercontent.com/11761863/97818584-129e5c00-1c58-11eb-8706-a9cd18f49fd6.png)
![unknown](https://user-images.githubusercontent.com/11761863/97818585-129e5c00-1c58-11eb-968d-668ce3b119c6.png)
![DiscordCanary_XCfzJ85apv](https://user-images.githubusercontent.com/11761863/97818588-18943d00-1c58-11eb-813b-8e046169d8d5.png)

**Comment by creepinson** [comment]
#23
