### ISSUE TITLE
[OTHER] - Determine initial file structure

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/TSProGen#5]
# Other Issue

## Files to Create

- [x] package.json
- [x] tsconfig.json
- [x] src/
- [x] src/index.ts
- [x] README.md
- [x] .gitignore

## Optional files

- [ ] .eslintrc.json
- [ ] .prettierrc
- [ ] .huskyrc

## Describe the issue

As a CLI call, this package will generate blank files and a file structure. That structure depends on what type of project this should generate. 

Initially, I propose we generate solely a back-end project with the following file structure: 
```md
- src
  | - server.ts
- package.json
- tsconfig.json
```

Do we want to include additional tooling configuration? And a `package.json`?

**Comment by SkyWolf369** [comment]
I believe we should add a tooling configuration and gen a package.json.

**Comment by nhcarrigan** [comment]
So we could mirror the file structure of this repo:

```md
- src
  | - server.ts
- package.json
- tsconfig.json
- .huskyrc
- .prettierrc
- .eslintrc.json
```

**Comment by SkyWolf369** [comment]
Yes but make husky prettier and eslint optional config.

**Comment by nhcarrigan** [comment]
Okay, so let's start with the initial file config in the issue body and get the CLI set up. Then we can look at adding optional flags to the CLI to generate the tooling files.

**Comment by SkyWolf369** [comment]
Sure.

**Comment by nhcarrigan** [comment]
I think we'll also want it to generate the `src` folder and insert an `index.ts` there, as well as a `.gitignore` to ignore the `node_modules` and `prod` folders.
